version: '3.4'

services:
  db:
     image: mysql:5.7
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: pokemondb
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: pikachu
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
  fundaychallenge:
    depends_on:
       - db
    image: ${DOCKER_REGISTRY}fundaychallenge
    build:
      context: .
      dockerfile: FundayChallenge/Dockerfile
    ports:
      - "8080:80"

volumes:
    dbdata: