version: '3.4'

services:
  db:
     image: mysql:latest
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: accountowner
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: dbuserpassword
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always
  fundaychallenge:
    depends_on:
      - db
    image: fundaychallenge
    build:
      context: ./Funday Challenge
      dockerfile: Dockerfile
